steps:
  # Build the container image
  - name: "gcr.io/cloud-builders/docker"
    args: ["build", "-t", "gcr.io/$PROJECT_ID/strapi-testing:$COMMIT_SHA", "."]
  # Push the container image to Container Registry
  - name: "gcr.io/cloud-builders/docker"
    args: ["push", "gcr.io/$PROJECT_ID/strapi-testing:$COMMIT_SHA"]
  # Deploy container image to Cloud Run
  - name: "gcr.io/google.com/cloudsdktool/cloud-sdk"
    entrypoint: gcloud
    args:
      - "run"
      - "deploy"
      - "strapi-testing"
      - "--image"
      - "gcr.io/$PROJECT_ID/strapi-testing:$COMMIT_SHA"
      - "--allow-unauthenticated"
      - "--max-instances"
      - "3"
      - "--region"
      - "asia-east1"
  # Create and mount volumn
  - name: "gcr.io/google.com/cloudsdktool/cloud-sdk"
    entrypoint: gcloud
    args:
      - "beta"
      - "run"
      - "services"
      - "update"
      - "strapi-testing"
      - "--execution-environment"
      - "gen2"
      - "--add-volume"
      - "name=sqlite-volme,type=cloud-storage,bucket=sqlite-volumn"
      - "--add-volume-mount"
      - "volume=sqlite-volme,mount-path=/sqlite"
      - "--region"
      - "asia-east1"
images:
  - "gcr.io/$PROJECT_ID/strapi-testing:$COMMIT_SHA"
